%% Wenjie Chen, 2016/06/13, FANUC Corporation
% To initilize the bus objects used to transfer customized bus-type signals

function cellInfo = init_bus_objects(varargin) 
% INIT_BUS_OBJECTS returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, SampleTime, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'ButtonState', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Green_Button', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LTT_Button', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'GripperCmd', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'GPR_MODE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SETUP', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'HOLD', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DRIVE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RESET', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SVON', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'GripperStatus', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'GPR_MODE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'BUSY', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'AREA', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SETON', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'INP', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SVRE', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ESTOP', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'ALARM', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'PosState', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Pos_J1_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_J2_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_J3_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_J4_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_J5_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_J6_deg', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_X_mm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_Y_mm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Pos_Z_mm', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'SysState', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'EtherCATOpState', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'M_State', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DSAbrakeCmd', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DSAin_MccOn', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'VRDY', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'DSAAxEtcInfoJ1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'tDSA_SysInfo2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'fDSA_SysInfo1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SafetyOver', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'TrqState', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', {... 
{'Trq_J1', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Trq_J2', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Trq_J3', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Trq_J4', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Trq_J5', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Trq_J6', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
