%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%     FANUC LRMate200iD/7L Robot CFS Simulator
%         load LTT data and save as a motion
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Created by Hsien-Chung Lin during FANUC internship in 2016
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% This function only loads the LTT_Data and initialize the motion,
% The submotion is generated by "SubMotionGenerate" and "XrefGenerate"
% 
% Data Format of "motion":
% DesJntPos  : [Nx6], N robot desired joint position  
% ReplayTime : [N-1], N-1 time vector
% GrpCmd     : [Nx6], N robot gripper command
% Marker_T_W : [4x4] or empty, AR tag's transformation matrix in world frame              
% MoFlag     : [N-1], indicate whether the robot is moving in each submotion
% traj       : [1xN-1] struct, the submotion, which has "extcmd" and "xref"
% 
% Data Formate of "submotion":
% traj.extcmd : [1x1] struct, similar to extcmd.
% traj.xref   : horizon x 1,  a vectorized downsampled joint position
%               reference.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function motion = loadLTTMotion2(filepath, filename, ActionName, robot_num)
filepath = [filepath,filename];
load(filepath);

motion.ActionName = ActionName;
varname = matlab.lang.makeValidName(['LTT_Data_',ActionName]); 
eval(['motion.DesJntPos = ',varname,'.DesJntPos{robot_num};']);
eval(['motion.ReplayTime = ',varname,'.ReplayTime{robot_num};']);
eval(['motion.GrpCmd = ',varname,'.GrpCmd{robot_num};']);
try
    eval(['motion.Marker_T_W = ',varname,'.Marker_T_W;']);
catch
    motion.Marker_T_W = [1 0 0 0;...
                         0 1 0 0;...
                         0 0 1 10;...
                         0 0 0 1];
end
ReplayTimeSize = length(motion.ReplayTime);

motion.MoFlag = zeros(ReplayTimeSize,1);


for r = 1:1
    for i = 1:ReplayTimeSize
        delta = norm( motion.DesJntPos(i+1,:) - motion.DesJntPos(i,:) );
        if delta >1, motion.MoFlag(i) = 1; end 
    end
end

